- name : loop
  hosts: localhost
  tasks: 
    - name : print city name
      debug: 
        msg: "all my city name : {{item}}"
      loop:
        - nag
        - pune
        - mumbai
        - chandrapur  
